apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-eks.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  labels:
    io.kompose.service: visits-service-java
  name: visits-service-java
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: visits-service-java
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject-java: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
        kompose.cmd: kompose convert -f ../docker-compose-eks.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      labels:
        io.kompose.service: visits-service-java

    spec:
      serviceAccountName: visits-service-account
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          env:
            - name: OTEL_INSTRUMENTATION_AWS_SDK_EXPERIMENTAL_SPAN_ATTRIBUTES
              value: "true"
          image: 111122223333.dkr.ecr.us-west-2.amazonaws.com/springcommunity/spring-petclinic-visits-service:latest
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          name: visits-service-java
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 12
      restartPolicy: Always
status: {}
